namespace Gmulator.Core.Gbc;

public partial class GbcCpu
{
    private void Step00(int op)
    {
        switch (op)
        {
            case 0x00: break;
            case 0x01: BC = OpLdImm16(); break;
            case 0x02: OpLdWr(BC, _a); break;
            case 0x03: BC = OpInc16(BC); break;
            case 0x04: _b = OpInc8(_b); break;
            case 0x05: _b = OpDec8(_b); break;
            case 0x06: _b = OpLdImm8(); break;
            case 0x07: OpRlca(); break;
            case 0x08: OpLdWr16(SP); break;
            case 0x09: HL = OpAdd(HL, BC); break;
            case 0x0a: _a = OpLdReg(BC); break;
            case 0x0b: BC = OpDec16(BC); break;
            case 0x0c: _c = OpInc8(_c); break;
            case 0x0d: _c = OpDec8(_c); break;
            case 0x0e: _c = OpLdImm8(); break;
            case 0x0f: OpRrca(); break;
            case 0x10: Ime = false; Halt = true; Stop = 8200; break;
            case 0x11: DE = OpLdImm16(); break;
            case 0x12: OpLdWr(DE, _a); break;
            case 0x13: DE = OpInc16(DE); break;
            case 0x14: _d = OpInc8(_d); break;
            case 0x15: _d = OpDec8(_d); break;
            case 0x16: _d = OpLdImm8(); break;
            case 0x17: OpRla(); break;
            case 0x18: OpJr(true); break;
            case 0x19: HL = OpAdd(HL, DE); break;
            case 0x1a: _a = OpLdReg(DE); break;
            case 0x1b: DE = OpDec16(DE); break;
            case 0x1c: _e = OpInc8(_e); break;
            case 0x1d: _e = OpDec8(_e); break;
            case 0x1e: _e = OpLdImm8(); break;
            case 0x1f: OpRra(); break;
            case 0x20: OpJr(!FlagZ); break;
            case 0x21: HL = OpLdImm16(); break;
            case 0x22: OpLdWr(HL++, _a); break;
            case 0x23: HL = OpInc16(HL); break;
            case 0x24: _h = OpInc8(_h); break;
            case 0x25: _h = OpDec8(_h); break;
            case 0x26: _h = OpLdImm8(); break;
            case 0x27: OpDaa(); break;
            case 0x28: OpJr(FlagZ); break;
            case 0x29: HL = OpAdd(HL, HL); break;
            case 0x2a: _a = OpLdReg(HL++); break;
            case 0x2b: HL = OpDec16(HL); break;
            case 0x2c: _l = OpInc8(_l); break;
            case 0x2d: _l = OpDec8(_l); break;
            case 0x2e: _l = OpLdImm8(); break;
            case 0x2f: OpCpl(); break;
            case 0x30: OpJr(!FlagC); break;
            case 0x31: SP = OpLdImm16(); break;
            case 0x32: OpLdWr(HL--, _a); break;
            case 0x33: SP = OpInc16(SP); break;
            case 0x34: OpLdWr(HL, OpInc8(OpLdReg(HL))); break;
            case 0x35: OpLdWr(HL, OpDec8(OpLdReg(HL))); break;
            case 0x36: OpLdWr(HL, OpLdImm8()); break;
            case 0x37: OpScf(); break;
            case 0x38: OpJr(FlagC); break;
            case 0x39: HL = OpAdd(HL, SP); break;
            case 0x3a: _a = OpLdReg(HL); HL--; break;
            case 0x3b: SP = OpDec16(SP); break;
            case 0x3c: _a = OpInc8(_a); break;
            case 0x3d: _a = OpDec8(_a); break;
            case 0x3e: _a = OpLdImm8(); break;
            case 0x3f: OpCcf(); break;
            case 0x40: break;
            case 0x41: _b = _c; break;
            case 0x42: _b = _d; break;
            case 0x43: _b = _e; break;
            case 0x44: _b = _h; break;
            case 0x45: _b = _l; break;
            case 0x46: _b = OpLdReg(HL); break;
            case 0x47: _b = _a; break;
            case 0x48: _c = _b; break;
            case 0x49: break;
            case 0x4a: _c = _d; break;
            case 0x4b: _c = _e; break;
            case 0x4c: _c = _h; break;
            case 0x4d: _c = _l; break;
            case 0x4e: _c = OpLdReg(HL); break;
            case 0x4f: _c = _a; break;
            case 0x50: _d = _b; break;
            case 0x51: _d = _c; break;
            case 0x52: break;
            case 0x53: _d = _e; break;
            case 0x54: _d = _h; break;
            case 0x55: _d = _l; break;
            case 0x56: _d = OpLdReg(HL); break;
            case 0x57: _d = _a; break;
            case 0x58: _e = _b; break;
            case 0x59: _e = _c; break;
            case 0x5a: _e = _d; break;
            case 0x5b: break;
            case 0x5c: _e = _h; break;
            case 0x5d: _e = _l; break;
            case 0x5e: _e = OpLdReg(HL); break;
            case 0x5f: _e = _a; break;
            case 0x60: _h = _b; break;
            case 0x61: _h = _c; break;
            case 0x62: _h = _d; break;
            case 0x63: _h = _e; break;
            case 0x64: break;
            case 0x65: _h = _l; break;
            case 0x66: _h = OpLdReg(HL); break;
            case 0x67: _h = _a; break;
            case 0x68: _l = _b; break;
            case 0x69: _l = _c; break;
            case 0x6a: _l = _d; break;
            case 0x6b: _l = _e; break;
            case 0x6c: _l = _h; break;
            case 0x6d: break;
            case 0x6e: _l = OpLdReg(HL); break;
            case 0x6f: _l = _a; break;
            case 0x70: OpLdWr(HL, _b); break;
            case 0x71: OpLdWr(HL, _c); break;
            case 0x72: OpLdWr(HL, _d); break;
            case 0x73: OpLdWr(HL, _e); break;
            case 0x74: OpLdWr(HL, _h); break;
            case 0x75: Halt = true; PC--; break;
            case 0x77: OpLdWr(HL, _a); break;
            case 0x78: _a = _b; break;
            case 0x79: _a = _c; break;
            case 0x7a: _a = _d; break;
            case 0x7b: _a = _e; break;
            case 0x7c: _a = _h; break;
            case 0x7d: _a = _l; break;
            case 0x7e: _a = OpLdReg(HL); break;
            case 0x7f: break;
            case 0x80: OpAdd8(_b); break;
            case 0x81: OpAdd8(_c); break;
            case 0x82: OpAdd8(_d); break;
            case 0x83: OpAdd8(_e); break;
            case 0x84: OpAdd8(_h); break;
            case 0x85: OpAdd8(_l); break;
            case 0x86: OpAdd8(OpLdReg(HL)); break;
            case 0x87: OpAdd8(_a); break;
            case 0x88: OpAdc8(_b); break;
            case 0x89: OpAdc8(_c); break;
            case 0x8a: OpAdc8(_d); break;
            case 0x8b: OpAdc8(_e); break;
            case 0x8c: OpAdc8(_h); break;
            case 0x8d: OpAdc8(_l); break;
            case 0x8e: OpAdc8(OpLdReg(HL)); break;
            case 0x8f: OpAdc8(_a); break;
            case 0x90: OpSub8(_b); break;
            case 0x91: OpSub8(_c); break;
            case 0x92: OpSub8(_d); break;
            case 0x93: OpSub8(_e); break;
            case 0x94: OpSub8(_h); break;
            case 0x95: OpSub8(_l); break;
            case 0x96: OpSub8(OpLdReg(HL)); break;
            case 0x97: OpSub8(_a); break;
            case 0x98: OpSbc8(_b); break;
            case 0x99: OpSbc8(_c); break;
            case 0x9a: OpSbc8(_d); break;
            case 0x9b: OpSbc8(_e); break;
            case 0x9c: OpSbc8(_h); break;
            case 0x9d: OpSbc8(_l); break;
            case 0x9e: OpSbc8(OpLdReg(HL)); break;
            case 0x9f: OpSbc8(_a); break;
            case 0xa0: OpAnd(_b); break;
            case 0xa1: OpAnd(_c); break;
            case 0xa2: OpAnd(_d); break;
            case 0xa3: OpAnd(_e); break;
            case 0xa4: OpAnd(_h); break;
            case 0xa5: OpAnd(_l); break;
            case 0xa6: OpAnd(OpLdReg(HL)); break;
            case 0xa7: OpAnd(_a); break;
            case 0xa8: OpXor(_b); break;
            case 0xa9: OpXor(_c); break;
            case 0xaa: OpXor(_d); break;
            case 0xab: OpXor(_e); break;
            case 0xac: OpXor(_h); break;
            case 0xad: OpXor(_l); break;
            case 0xae: OpXor(OpLdReg(HL)); break;
            case 0xaf: OpXor(_a); break;
            case 0xb0: OpOr(_b); break;
            case 0xb1: OpOr(_c); break;
            case 0xb2: OpOr(_d); break;
            case 0xb3: OpOr(_e); break;
            case 0xb4: OpOr(_h); break;
            case 0xb5: OpOr(_l); break;
            case 0xb6: OpOr(OpLdReg(HL)); break;
            case 0xb7: OpOr(_a); break;
            case 0xb8: OpCp(_b); break;
            case 0xb9: OpCp(_c); break;
            case 0xba: OpCp(_d); break;
            case 0xbb: OpCp(_e); break;
            case 0xbc: OpCp(_h); break;
            case 0xbd: OpCp(_l); break;
            case 0xbe: OpCp(OpLdReg(HL)); break;
            case 0xbf: OpCp(_a); break;
            case 0xc0: OpRet(!FlagZ); break;
            case 0xc1: BC = OpPop(); break;
            case 0xc2: OpJp(!FlagZ); break;
            case 0xc3: OpJp(true); break;
            case 0xc4: OpCall(!FlagZ); break;
            case 0xc5: Tick(); OpPush(BC); break;
            case 0xc6: OpAdd8(OpLdImm8()); break;
            case 0xc7: OpRst(0x00); break;
            case 0xc8: OpRet(FlagZ); break;
            case 0xc9: OpRet(true, true); break;
            case 0xca: OpJp(FlagZ); break;
            case 0xcb: break;
            case 0xcc: OpCall(FlagZ); break;
            case 0xcd: OpCall(true); break;
            case 0xce: OpAdc8(OpLdImm8()); break;
            case 0xcf: OpRst(0x08); break;
            case 0xd0: OpRet(!FlagC); break;
            case 0xd1: DE = OpPop(); break;
            case 0xd2: OpJp(!FlagC); break;
            case 0xd3: break;
            case 0xd4: OpCall(!FlagC); break;
            case 0xd5: Tick(); OpPush(DE); break;
            case 0xd6: OpSub8(OpLdImm8()); break;
            case 0xd7: OpRst(0x10); break;
            case 0xd8: OpRet(FlagC); break;
            case 0xd9: OpReti(); break;
            case 0xda: OpJp(FlagC); break;
            case 0xdb: break;
            case 0xdc: OpCall(FlagC); break;
            case 0xdd: break;
            case 0xde: OpSbc8(OpLdImm8()); break;
            case 0xdf: OpRst(0x18); break;
            case 0xe0: OpLdWr((ushort)(0xff00 + OpLdImm8()), _a); break;
            case 0xe1: HL = OpPop(); break;
            case 0xe2: OpLdWr((ushort)(0xff00 + _c), _a); break;
            case 0xe3: break;
            case 0xe4: break;
            case 0xe5: Tick(); OpPush(HL); break;
            case 0xe6: OpAnd(OpLdImm8()); break;
            case 0xe7: OpRst(0x20); break;
            case 0xe8: SP = OpAddSP(SP, (sbyte)OpLdImm8()); break;
            case 0xe9: PC = HL; break;
            case 0xea: OpLdWr(OpLdImm16(), _a); break;
            case 0xeb or 0xec or 0xed: break;
            case 0xee: OpXor(OpLdImm8()); break;
            case 0xef: OpRst(0x28); break;
            case 0xf0: _a = OpLdReg((ushort)(0xff00 + OpLdImm8())); break;
            case 0xf1: AF = OpPop(true); break;
            case 0xf2: _a = OpLdReg((ushort)(0xff00 + _c)); break;
            case 0xf3: OpDI(); break;
            case 0xf4: break;
            case 0xf5: Tick(); OpPush(AF); break;
            case 0xf6: OpOr(OpLdImm8()); break;
            case 0xf7: OpRst(0x30); break;
            case 0xf8: HL = OpLdHLSP(SP, (sbyte)OpLdImm8()); break;
            case 0xf9: { Tick(); SP = HL; }; break;
            case 0xfa: _a = OpLdReg(OpLdImm16()); break;
            case 0xfb: OpEI(); break;
            case 0xfc or 0xfd: break;
            case 0xfe: OpCp(OpLdImm8()); break;
            case 0xff: OpRst(0x38); break;
        }
    }

    private void StepCB(int op)
    {
        switch (op)
        {
            case 0x00: _b = OpRlc(_b); break;
            case 0x01: _c = OpRlc(_c); break;
            case 0x02: _d = OpRlc(_d); break;
            case 0x03: _e = OpRlc(_e); break;
            case 0x04: _h = OpRlc(_h); break;
            case 0x05: _l = OpRlc(_l); break;
            case 0x06: OpLdWr(HL, OpRlc(OpLdReg(HL))); break;
            case 0x07: _a = OpRlc(_a); break;
            case 0x08: _b = OpRrc(_b); break;
            case 0x09: _c = OpRrc(_c); break;
            case 0x0a: _d = OpRrc(_d); break;
            case 0x0b: _e = OpRrc(_e); break;
            case 0x0c: _h = OpRrc(_h); break;
            case 0x0d: _l = OpRrc(_l); break;
            case 0x0e: OpLdWr(HL, OpRrc(OpLdReg(HL))); break;
            case 0x0f: _a = OpRrc(_a); break;
            case 0x10: _b = OpRl(_b); break;
            case 0x11: _c = OpRl(_c); break;
            case 0x12: _d = OpRl(_d); break;
            case 0x13: _e = OpRl(_e); break;
            case 0x14: _h = OpRl(_h); break;
            case 0x15: _l = OpRl(_l); break;
            case 0x16: OpLdWr(HL, OpRl(OpLdReg(HL))); break;
            case 0x17: _a = OpRl(_a); break;
            case 0x18: _b = OpRr(_b); break;
            case 0x19: _c = OpRr(_c); break;
            case 0x1a: _d = OpRr(_d); break;
            case 0x1b: _e = OpRr(_e); break;
            case 0x1c: _h = OpRr(_h); break;
            case 0x1d: _l = OpRr(_l); break;
            case 0x1e: OpLdWr(HL, OpRr(OpLdReg(HL))); break;
            case 0x1f: _a = OpRr(_a); break;
            case 0x20: _b = OpSla(_b); break;
            case 0x21: _c = OpSla(_c); break;
            case 0x22: _d = OpSla(_d); break;
            case 0x23: _e = OpSla(_e); break;
            case 0x24: _h = OpSla(_h); break;
            case 0x25: _l = OpSla(_l); break;
            case 0x26: OpLdWr(HL, OpSla(OpLdReg(HL))); break;
            case 0x27: _a = OpSla(_a); break;
            case 0x28: _b = OpSra(_b); break;
            case 0x29: _c = OpSra(_c); break;
            case 0x2a: _d = OpSra(_d); break;
            case 0x2b: _e = OpSra(_e); break;
            case 0x2c: _h = OpSra(_h); break;
            case 0x2d: _l = OpSra(_l); break;
            case 0x2e: OpLdWr(HL, OpSra(OpLdReg(HL))); break;
            case 0x2f: _a = OpSra(_a); break;
            case 0x30: _b = OpSwap(_b); break;
            case 0x31: _c = OpSwap(_c); break;
            case 0x32: _d = OpSwap(_d); break;
            case 0x33: _e = OpSwap(_e); break;
            case 0x34: _h = OpSwap(_h); break;
            case 0x35: _l = OpSwap(_l); break;
            case 0x36: OpLdWr(HL, OpSwap(OpLdReg(HL))); break;
            case 0x37: _a = OpSwap(_a); break;
            case 0x38: _b = OpSrl(_b); break;
            case 0x39: _c = OpSrl(_c); break;
            case 0x3a: _d = OpSrl(_d); break;
            case 0x3b: _e = OpSrl(_e); break;
            case 0x3c: _h = OpSrl(_h); break;
            case 0x3d: _l = OpSrl(_l); break;
            case 0x3e: OpLdWr(HL, OpSrl(OpLdReg(HL))); break;
            case 0x3f: _a = OpSrl(_a); break;
            case 0x40: OpBit(0, _b); break;
            case 0x41: OpBit(0, _c); break;
            case 0x42: OpBit(0, _d); break;
            case 0x43: OpBit(0, _e); break;
            case 0x44: OpBit(0, _h); break;
            case 0x45: OpBit(0, _l); break;
            case 0x46: OpBit(0, OpLdReg(HL)); break;
            case 0x47: OpBit(0, _a); break;
            case 0x48: OpBit(1, _b); break;
            case 0x49: OpBit(1, _c); break;
            case 0x4a: OpBit(1, _d); break;
            case 0x4b: OpBit(1, _e); break;
            case 0x4c: OpBit(1, _h); break;
            case 0x4d: OpBit(1, _l); break;
            case 0x4e: OpBit(1, OpLdReg(HL)); break;
            case 0x4f: OpBit(1, _a); break;
            case 0x50: OpBit(2, _b); break;
            case 0x51: OpBit(2, _c); break;
            case 0x52: OpBit(2, _d); break;
            case 0x53: OpBit(2, _e); break;
            case 0x54: OpBit(2, _h); break;
            case 0x55: OpBit(2, _l); break;
            case 0x56: OpBit(2, OpLdReg(HL)); break;
            case 0x57: OpBit(2, _a); break;
            case 0x58: OpBit(3, _b); break;
            case 0x59: OpBit(3, _c); break;
            case 0x5a: OpBit(3, _d); break;
            case 0x5b: OpBit(3, _e); break;
            case 0x5c: OpBit(3, _h); break;
            case 0x5d: OpBit(3, _l); break;
            case 0x5e: OpBit(3, OpLdReg(HL)); break;
            case 0x5f: OpBit(3, _a); break;
            case 0x60: OpBit(4, _b); break;
            case 0x61: OpBit(4, _c); break;
            case 0x62: OpBit(4, _d); break;
            case 0x63: OpBit(4, _e); break;
            case 0x64: OpBit(4, _h); break;
            case 0x65: OpBit(4, _l); break;
            case 0x66: OpBit(4, OpLdReg(HL)); break;
            case 0x67: OpBit(4, _a); break;
            case 0x68: OpBit(5, _b); break;
            case 0x69: OpBit(5, _c); break;
            case 0x6a: OpBit(5, _d); break;
            case 0x6b: OpBit(5, _e); break;
            case 0x6c: OpBit(5, _h); break;
            case 0x6d: OpBit(5, _l); break;
            case 0x6e: OpBit(5, OpLdReg(HL)); break;
            case 0x6f: OpBit(5, _a); break;
            case 0x70: OpBit(6, _b); break;
            case 0x71: OpBit(6, _c); break;
            case 0x72: OpBit(6, _d); break;
            case 0x73: OpBit(6, _e); break;
            case 0x74: OpBit(6, _h); break;
            case 0x75: OpBit(6, _l); break;
            case 0x76: OpBit(6, OpLdReg(HL)); break;
            case 0x77: OpBit(6, _a); break;
            case 0x78: OpBit(7, _b); break;
            case 0x79: OpBit(7, _c); break;
            case 0x7a: OpBit(7, _d); break;
            case 0x7b: OpBit(7, _e); break;
            case 0x7c: OpBit(7, _h); break;
            case 0x7d: OpBit(7, _l); break;
            case 0x7e: OpBit(7, OpLdReg(HL)); break;
            case 0x7f: OpBit(7, _a); break;
            case 0x80: _b = OpRes(0, _b); break;
            case 0x81: _c = OpRes(0, _c); break;
            case 0x82: _d = OpRes(0, _d); break;
            case 0x83: _e = OpRes(0, _e); break;
            case 0x84: _h = OpRes(0, _h); break;
            case 0x85: _l = OpRes(0, _l); break;
            case 0x86: OpResHL(0); break;
            case 0x87: _a = OpRes(0, _a); break;
            case 0x88: _b = OpRes(1, _b); break;
            case 0x89: _c = OpRes(1, _c); break;
            case 0x8a: _d = OpRes(1, _d); break;
            case 0x8b: _e = OpRes(1, _e); break;
            case 0x8c: _h = OpRes(1, _h); break;
            case 0x8d: _l = OpRes(1, _l); break;
            case 0x8e: OpResHL(1); break;
            case 0x8f: _a = OpRes(1, _a); break;
            case 0x90: _b = OpRes(2, _b); break;
            case 0x91: _c = OpRes(2, _c); break;
            case 0x92: _d = OpRes(2, _d); break;
            case 0x93: _e = OpRes(2, _e); break;
            case 0x94: _h = OpRes(2, _h); break;
            case 0x95: _l = OpRes(2, _l); break;
            case 0x96: OpResHL(2); break;
            case 0x97: _a = OpRes(2, _a); break;
            case 0x98: _b = OpRes(3, _b); break;
            case 0x99: _c = OpRes(3, _c); break;
            case 0x9a: _d = OpRes(3, _d); break;
            case 0x9b: _e = OpRes(3, _e); break;
            case 0x9c: _h = OpRes(3, _h); break;
            case 0x9d: _l = OpRes(3, _l); break;
            case 0x9e: OpResHL(3); break;
            case 0x9f: _a = OpRes(3, _a); break;
            case 0xa0: _b = OpRes(4, _b); break;
            case 0xa1: _c = OpRes(4, _c); break;
            case 0xa2: _d = OpRes(4, _d); break;
            case 0xa3: _e = OpRes(4, _e); break;
            case 0xa4: _h = OpRes(4, _h); break;
            case 0xa5: _l = OpRes(4, _l); break;
            case 0xa6: OpResHL(4); break;
            case 0xa7: _a = OpRes(4, _a); break;
            case 0xa8: _b = OpRes(5, _b); break;
            case 0xa9: _c = OpRes(5, _c); break;
            case 0xaa: _d = OpRes(5, _d); break;
            case 0xab: _e = OpRes(5, _e); break;
            case 0xac: _h = OpRes(5, _h); break;
            case 0xad: _l = OpRes(5, _l); break;
            case 0xae: OpResHL(5); break;
            case 0xaf: _a = OpRes(5, _a); break;
            case 0xb0: _b = OpRes(6, _b); break;
            case 0xb1: _c = OpRes(6, _c); break;
            case 0xb2: _d = OpRes(6, _d); break;
            case 0xb3: _e = OpRes(6, _e); break;
            case 0xb4: _h = OpRes(6, _h); break;
            case 0xb5: _l = OpRes(6, _l); break;
            case 0xb6: OpResHL(6); break;
            case 0xb7: _a = OpRes(6, _a); break;
            case 0xb8: _b = OpRes(7, _b); break;
            case 0xb9: _c = OpRes(7, _c); break;
            case 0xba: _d = OpRes(7, _d); break;
            case 0xbb: _e = OpRes(7, _e); break;
            case 0xbc: _h = OpRes(7, _h); break;
            case 0xbd: _l = OpRes(7, _l); break;
            case 0xbe: OpResHL(7); break;
            case 0xbf: _a = OpRes(7, _a); break;
            case 0xc0: _b = OpSet(0, _b); break;
            case 0xc1: _c = OpSet(0, _c); break;
            case 0xc2: _d = OpSet(0, _d); break;
            case 0xc3: _e = OpSet(0, _e); break;
            case 0xc4: _h = OpSet(0, _h); break;
            case 0xc5: _l = OpSet(0, _l); break;
            case 0xc6: OpSetHL(0); break;
            case 0xc7: _a = OpSet(0, _a); break;
            case 0xc8: _b = OpSet(1, _b); break;
            case 0xc9: _c = OpSet(1, _c); break;
            case 0xca: _d = OpSet(1, _d); break;
            case 0xcb: _e = OpSet(1, _e); break;
            case 0xcc: _h = OpSet(1, _h); break;
            case 0xcd: _l = OpSet(1, _l); break;
            case 0xce: OpSetHL(1); break;
            case 0xcf: _a = OpSet(1, _a); break;
            case 0xd0: _b = OpSet(2, _b); break;
            case 0xd1: _c = OpSet(2, _c); break;
            case 0xd2: _d = OpSet(2, _d); break;
            case 0xd3: _e = OpSet(2, _e); break;
            case 0xd4: _h = OpSet(2, _h); break;
            case 0xd5: _l = OpSet(2, _l); break;
            case 0xd6: OpSetHL(2); break;
            case 0xd7: _a = OpSet(2, _a); break;
            case 0xd8: _b = OpSet(3, _b); break;
            case 0xd9: _c = OpSet(3, _c); break;
            case 0xda: _d = OpSet(3, _d); break;
            case 0xdb: _e = OpSet(3, _e); break;
            case 0xdc: _h = OpSet(3, _h); break;
            case 0xdd: _l = OpSet(3, _l); break;
            case 0xde: OpSetHL(3); break;
            case 0xdf: _a = OpSet(3, _a); break;
            case 0xe0: _b = OpSet(4, _b); break;
            case 0xe1: _c = OpSet(4, _c); break;
            case 0xe2: _d = OpSet(4, _d); break;
            case 0xe3: _e = OpSet(4, _e); break;
            case 0xe4: _h = OpSet(4, _h); break;
            case 0xe5: _l = OpSet(4, _l); break;
            case 0xe6: OpSetHL(4); break;
            case 0xe7: _a = OpSet(4, _a); break;
            case 0xe8: _b = OpSet(5, _b); break;
            case 0xe9: _c = OpSet(5, _c); break;
            case 0xea: _d = OpSet(5, _d); break;
            case 0xeb: _e = OpSet(5, _e); break;
            case 0xec: _h = OpSet(5, _h); break;
            case 0xed: _l = OpSet(5, _l); break;
            case 0xee: OpSetHL(5); break;
            case 0xef: _a = OpSet(5, _a); break;
            case 0xf0: _b = OpSet(6, _b); break;
            case 0xf1: _c = OpSet(6, _c); break;
            case 0xf2: _d = OpSet(6, _d); break;
            case 0xf3: _e = OpSet(6, _e); break;
            case 0xf4: _h = OpSet(6, _h); break;
            case 0xf5: _l = OpSet(6, _l); break;
            case 0xf6: OpSetHL(6); break;
            case 0xf7: _a = OpSet(6, _a); break;
            case 0xf8: _b = OpSet(7, _b); break;
            case 0xf9: _c = OpSet(7, _c); break;
            case 0xfa: _d = OpSet(7, _d); break;
            case 0xfb: _e = OpSet(7, _e); break;
            case 0xfc: _h = OpSet(7, _h); break;
            case 0xfd: _l = OpSet(7, _l); break;
            case 0xfe: OpSetHL(7); break;
            case 0xff: _a = OpSet(7, _a); break;
        }
    }
}
