
namespace GBoy.Core;
public partial class GbcCpu
{
    public struct Opcode
    {
        public string Name;
        public string Oper;
        public string Format;
        public byte Size;
             
        public Opcode(string name, string oper, string format, byte size)
        {
            Name = name;
            Oper = oper;
            Format = format;
            Size = size;
        }
    }
    
	public static List<Opcode> OpInfo00;
	public static List<Opcode> OpInfoCB;

    public void GenerateOpInfo()
	{
		OpInfo00 = new();
		OpInfoCB = new();

		OpInfo00.Add(new Opcode("nop", "n/a", "", 1)); //00
		OpInfo00.Add(new Opcode("ld", "bc,", "x4", 3)); //01
		OpInfo00.Add(new Opcode("ld", "(bc),a", "", 1)); //02
		OpInfo00.Add(new Opcode("inc", "bc", "", 1)); //03
		OpInfo00.Add(new Opcode("inc", "b", "", 1)); //04
		OpInfo00.Add(new Opcode("dec", "b", "", 1)); //05
		OpInfo00.Add(new Opcode("ld", "b,", "x2", 2)); //06
		OpInfo00.Add(new Opcode("rlca", "n/a", "", 1)); //07
		OpInfo00.Add(new Opcode("ld", "sp", "x4", 3)); //08
		OpInfo00.Add(new Opcode("add", "hl,bc", "", 1)); //09
		OpInfo00.Add(new Opcode("ld", "a,(bc)", "", 1)); //0A
		OpInfo00.Add(new Opcode("dec", "bc", "", 1)); //0B
		OpInfo00.Add(new Opcode("inc", "c", "", 1)); //0C
		OpInfo00.Add(new Opcode("dec", "c", "", 1)); //0D
		OpInfo00.Add(new Opcode("ld", "c,", "x2", 2)); //0E
		OpInfo00.Add(new Opcode("rrca", "n/a", "", 1)); //0F
		OpInfo00.Add(new Opcode("stop", "0", "", 2)); //10
		OpInfo00.Add(new Opcode("ld", "de,", "x4", 3)); //11
		OpInfo00.Add(new Opcode("ld", "(de),a", "", 1)); //12
		OpInfo00.Add(new Opcode("inc", "de", "", 1)); //13
		OpInfo00.Add(new Opcode("inc", "d", "", 1)); //14
		OpInfo00.Add(new Opcode("dec", "d", "", 1)); //15
		OpInfo00.Add(new Opcode("ld", "d,", "x2", 2)); //16
		OpInfo00.Add(new Opcode("rla", "n/a", "", 1)); //17
		OpInfo00.Add(new Opcode("jr", "", "x4", 2)); //18
		OpInfo00.Add(new Opcode("add", "hl,de", "", 1)); //19
		OpInfo00.Add(new Opcode("ld", "a,(de)", "", 1)); //1A
		OpInfo00.Add(new Opcode("dec", "de", "", 1)); //1B
		OpInfo00.Add(new Opcode("inc", "e", "", 1)); //1C
		OpInfo00.Add(new Opcode("dec", "e", "", 1)); //1D
		OpInfo00.Add(new Opcode("ld", "e,", "x2", 2)); //1E
		OpInfo00.Add(new Opcode("rra", "n/a", "", 1)); //1F
		OpInfo00.Add(new Opcode("jr", "nz,", "x4", 2)); //20
		OpInfo00.Add(new Opcode("ld", "hl,", "x4", 3)); //21
		OpInfo00.Add(new Opcode("ld", "(hl+),a", "", 1)); //22
		OpInfo00.Add(new Opcode("inc", "hl", "", 1)); //23
		OpInfo00.Add(new Opcode("inc", "h", "", 1)); //24
		OpInfo00.Add(new Opcode("dec", "h", "", 1)); //25
		OpInfo00.Add(new Opcode("ld", "h,", "x2", 2)); //26
		OpInfo00.Add(new Opcode("daa", "n/a", "", 1)); //27
		OpInfo00.Add(new Opcode("jr", "z,", "x4", 2)); //28
		OpInfo00.Add(new Opcode("add", "hl,hl", "", 1)); //29
		OpInfo00.Add(new Opcode("ld", "a,(hl+)", "", 1)); //2A
		OpInfo00.Add(new Opcode("dec", "hl", "", 1)); //2B
		OpInfo00.Add(new Opcode("inc", "l", "", 1)); //2C
		OpInfo00.Add(new Opcode("dec", "l", "", 1)); //2D
		OpInfo00.Add(new Opcode("ld", "l,", "x2", 2)); //2E
		OpInfo00.Add(new Opcode("cpl", "n/a", "", 1)); //2F
		OpInfo00.Add(new Opcode("jr", "nc,", "x4", 2)); //30
		OpInfo00.Add(new Opcode("ld", "sp,", "x4", 3)); //31
		OpInfo00.Add(new Opcode("ld", "(hl-),a", "", 1)); //32
		OpInfo00.Add(new Opcode("inc", "sp", "", 1)); //33
		OpInfo00.Add(new Opcode("inc", "(hl)", "", 1)); //34
		OpInfo00.Add(new Opcode("dec", "(hl)", "", 1)); //35
		OpInfo00.Add(new Opcode("ld", "(hl),", "x2", 2)); //36
		OpInfo00.Add(new Opcode("scf", "n/a", "", 1)); //37
		OpInfo00.Add(new Opcode("jr", "c,", "x4", 2)); //38
		OpInfo00.Add(new Opcode("add", "hl,sp", "", 1)); //39
		OpInfo00.Add(new Opcode("ld", "a,(hl-)", "", 1)); //3A
		OpInfo00.Add(new Opcode("dec", "sp", "", 1)); //3B
		OpInfo00.Add(new Opcode("inc", "a", "", 1)); //3C
		OpInfo00.Add(new Opcode("dec", "a", "", 1)); //3D
		OpInfo00.Add(new Opcode("ld", "a,", "x2", 2)); //3E
		OpInfo00.Add(new Opcode("ccf", "n/a", "", 1)); //3F
		OpInfo00.Add(new Opcode("ld", "b,b", "", 1)); //40
		OpInfo00.Add(new Opcode("ld", "b,c", "", 1)); //41
		OpInfo00.Add(new Opcode("ld", "b,d", "", 1)); //42
		OpInfo00.Add(new Opcode("ld", "b,e", "", 1)); //43
		OpInfo00.Add(new Opcode("ld", "b,h", "", 1)); //44
		OpInfo00.Add(new Opcode("ld", "b,l", "", 1)); //45
		OpInfo00.Add(new Opcode("ld", "b,(hl)", "", 1)); //46
		OpInfo00.Add(new Opcode("ld", "b,a", "", 1)); //47
		OpInfo00.Add(new Opcode("ld", "c,b", "", 1)); //48
		OpInfo00.Add(new Opcode("ld", "c,c", "", 1)); //49
		OpInfo00.Add(new Opcode("ld", "c,d", "", 1)); //4A
		OpInfo00.Add(new Opcode("ld", "c,e", "", 1)); //4B
		OpInfo00.Add(new Opcode("ld", "c,h", "", 1)); //4C
		OpInfo00.Add(new Opcode("ld", "c,l", "", 1)); //4D
		OpInfo00.Add(new Opcode("ld", "c,(hl)", "", 1)); //4E
		OpInfo00.Add(new Opcode("ld", "c,a", "", 1)); //4F
		OpInfo00.Add(new Opcode("ld", "d,b", "", 1)); //50
		OpInfo00.Add(new Opcode("ld", "d,c", "", 1)); //51
		OpInfo00.Add(new Opcode("ld", "d,d", "", 1)); //52
		OpInfo00.Add(new Opcode("ld", "d,e", "", 1)); //53
		OpInfo00.Add(new Opcode("ld", "d,h", "", 1)); //54
		OpInfo00.Add(new Opcode("ld", "d,l", "", 1)); //55
		OpInfo00.Add(new Opcode("ld", "d,(hl)", "", 1)); //56
		OpInfo00.Add(new Opcode("ld", "d,a", "", 1)); //57
		OpInfo00.Add(new Opcode("ld", "e,b", "", 1)); //58
		OpInfo00.Add(new Opcode("ld", "e,c", "", 1)); //59
		OpInfo00.Add(new Opcode("ld", "e,d", "", 1)); //5A
		OpInfo00.Add(new Opcode("ld", "e,e", "", 1)); //5B
		OpInfo00.Add(new Opcode("ld", "e,h", "", 1)); //5C
		OpInfo00.Add(new Opcode("ld", "e,l", "", 1)); //5D
		OpInfo00.Add(new Opcode("ld", "e,(hl)", "", 1)); //5E
		OpInfo00.Add(new Opcode("ld", "e,a", "", 1)); //5F
		OpInfo00.Add(new Opcode("ld", "h,b", "", 1)); //60
		OpInfo00.Add(new Opcode("ld", "h,c", "", 1)); //61
		OpInfo00.Add(new Opcode("ld", "h,d", "", 1)); //62
		OpInfo00.Add(new Opcode("ld", "h,e", "", 1)); //63
		OpInfo00.Add(new Opcode("ld", "h,h", "", 1)); //64
		OpInfo00.Add(new Opcode("ld", "h,l", "", 1)); //65
		OpInfo00.Add(new Opcode("ld", "h,(hl)", "", 1)); //66
		OpInfo00.Add(new Opcode("ld", "h,a", "", 1)); //67
		OpInfo00.Add(new Opcode("ld", "l,b", "", 1)); //68
		OpInfo00.Add(new Opcode("ld", "l,c", "", 1)); //69
		OpInfo00.Add(new Opcode("ld", "l,d", "", 1)); //6A
		OpInfo00.Add(new Opcode("ld", "l,e", "", 1)); //6B
		OpInfo00.Add(new Opcode("ld", "l,h", "", 1)); //6C
		OpInfo00.Add(new Opcode("ld", "l,l", "", 1)); //6D
		OpInfo00.Add(new Opcode("ld", "l,(hl)", "", 1)); //6E
		OpInfo00.Add(new Opcode("ld", "l,a", "", 1)); //6F
		OpInfo00.Add(new Opcode("ld", "(hl),b", "", 1)); //70
		OpInfo00.Add(new Opcode("ld", "(hl),c", "", 1)); //71
		OpInfo00.Add(new Opcode("ld", "(hl),d", "", 1)); //72
		OpInfo00.Add(new Opcode("ld", "(hl),e", "", 1)); //73
		OpInfo00.Add(new Opcode("ld", "(hl),h", "", 1)); //74
		OpInfo00.Add(new Opcode("ld", "(hl),l", "", 1)); //75
		OpInfo00.Add(new Opcode("halt", "n/a", "", 1)); //76
		OpInfo00.Add(new Opcode("ld", "(hl),a", "", 1)); //77
		OpInfo00.Add(new Opcode("ld", "a,b", "", 1)); //78
		OpInfo00.Add(new Opcode("ld", "a,c", "", 1)); //79
		OpInfo00.Add(new Opcode("ld", "a,d", "", 1)); //7A
		OpInfo00.Add(new Opcode("ld", "a,e", "", 1)); //7B
		OpInfo00.Add(new Opcode("ld", "a,h", "", 1)); //7C
		OpInfo00.Add(new Opcode("ld", "a,l", "", 1)); //7D
		OpInfo00.Add(new Opcode("ld", "a,(hl)", "", 1)); //7E
		OpInfo00.Add(new Opcode("ld", "a,a", "", 1)); //7F
		OpInfo00.Add(new Opcode("add", "a,b", "", 1)); //80
		OpInfo00.Add(new Opcode("add", "a,c", "", 1)); //81
		OpInfo00.Add(new Opcode("add", "a,d", "", 1)); //82
		OpInfo00.Add(new Opcode("add", "a,e", "", 1)); //83
		OpInfo00.Add(new Opcode("add", "a,h", "", 1)); //84
		OpInfo00.Add(new Opcode("add", "a,l", "", 1)); //85
		OpInfo00.Add(new Opcode("add", "a,(hl)", "", 1)); //86
		OpInfo00.Add(new Opcode("add", "a,a", "", 1)); //87
		OpInfo00.Add(new Opcode("adc", "a,b", "", 1)); //88
		OpInfo00.Add(new Opcode("adc", "a,c", "", 1)); //89
		OpInfo00.Add(new Opcode("adc", "a,d", "", 1)); //8A
		OpInfo00.Add(new Opcode("adc", "a,e", "", 1)); //8B
		OpInfo00.Add(new Opcode("adc", "a,h", "", 1)); //8C
		OpInfo00.Add(new Opcode("adc", "a,l", "", 1)); //8D
		OpInfo00.Add(new Opcode("adc", "a,(hl)", "", 1)); //8E
		OpInfo00.Add(new Opcode("adc", "a,a", "", 1)); //8F
		OpInfo00.Add(new Opcode("sub", "b", "", 1)); //90
		OpInfo00.Add(new Opcode("sub", "c", "", 1)); //91
		OpInfo00.Add(new Opcode("sub", "d", "", 1)); //92
		OpInfo00.Add(new Opcode("sub", "e", "", 1)); //93
		OpInfo00.Add(new Opcode("sub", "h", "", 1)); //94
		OpInfo00.Add(new Opcode("sub", "l", "", 1)); //95
		OpInfo00.Add(new Opcode("sub", "(hl)", "", 1)); //96
		OpInfo00.Add(new Opcode("sub", "a", "", 1)); //97
		OpInfo00.Add(new Opcode("sbc", "a,b", "", 1)); //98
		OpInfo00.Add(new Opcode("sbc", "a,c", "", 1)); //99
		OpInfo00.Add(new Opcode("sbc", "a,d", "", 1)); //9A
		OpInfo00.Add(new Opcode("sbc", "a,e", "", 1)); //9B
		OpInfo00.Add(new Opcode("sbc", "a,h", "", 1)); //9C
		OpInfo00.Add(new Opcode("sbc", "a,l", "", 1)); //9D
		OpInfo00.Add(new Opcode("sbc", "a,(hl)", "", 1)); //9E
		OpInfo00.Add(new Opcode("sbc", "a,a", "", 1)); //9F
		OpInfo00.Add(new Opcode("and", "b", "", 1)); //A0
		OpInfo00.Add(new Opcode("and", "c", "", 1)); //A1
		OpInfo00.Add(new Opcode("and", "d", "", 1)); //A2
		OpInfo00.Add(new Opcode("and", "e", "", 1)); //A3
		OpInfo00.Add(new Opcode("and", "h", "", 1)); //A4
		OpInfo00.Add(new Opcode("and", "l", "", 1)); //A5
		OpInfo00.Add(new Opcode("and", "(hl)", "", 1)); //A6
		OpInfo00.Add(new Opcode("and", "a", "", 1)); //A7
		OpInfo00.Add(new Opcode("xor", "b", "", 1)); //A8
		OpInfo00.Add(new Opcode("xor", "c", "", 1)); //A9
		OpInfo00.Add(new Opcode("xor", "d", "", 1)); //AA
		OpInfo00.Add(new Opcode("xor", "e", "", 1)); //AB
		OpInfo00.Add(new Opcode("xor", "h", "", 1)); //AC
		OpInfo00.Add(new Opcode("xor", "l", "", 1)); //AD
		OpInfo00.Add(new Opcode("xor", "(hl)", "", 1)); //AE
		OpInfo00.Add(new Opcode("xor", "a", "", 1)); //AF
		OpInfo00.Add(new Opcode("or", "b", "", 1)); //B0
		OpInfo00.Add(new Opcode("or", "c", "", 1)); //B1
		OpInfo00.Add(new Opcode("or", "d", "", 1)); //B2
		OpInfo00.Add(new Opcode("or", "e", "", 1)); //B3
		OpInfo00.Add(new Opcode("or", "h", "", 1)); //B4
		OpInfo00.Add(new Opcode("or", "l", "", 1)); //B5
		OpInfo00.Add(new Opcode("or", "(hl)", "", 1)); //B6
		OpInfo00.Add(new Opcode("or", "a", "", 1)); //B7
		OpInfo00.Add(new Opcode("cp", "b", "", 1)); //B8
		OpInfo00.Add(new Opcode("cp", "c", "", 1)); //B9
		OpInfo00.Add(new Opcode("cp", "d", "", 1)); //BA
		OpInfo00.Add(new Opcode("cp", "e", "", 1)); //BB
		OpInfo00.Add(new Opcode("cp", "h", "", 1)); //BC
		OpInfo00.Add(new Opcode("cp", "l", "", 1)); //BD
		OpInfo00.Add(new Opcode("cp", "(hl)", "", 1)); //BE
		OpInfo00.Add(new Opcode("cp", "a", "", 1)); //BF
		OpInfo00.Add(new Opcode("ret", "nz", "", 1)); //C0
		OpInfo00.Add(new Opcode("pop", "bc", "", 1)); //C1
		OpInfo00.Add(new Opcode("jp", "", "x4", 3)); //C2
		OpInfo00.Add(new Opcode("jp", "", "x4", 3)); //C3
		OpInfo00.Add(new Opcode("call", "", "x4", 3)); //C4
		OpInfo00.Add(new Opcode("push", "bc", "", 1)); //C5
		OpInfo00.Add(new Opcode("add", "a,", "x2", 2)); //C6
		OpInfo00.Add(new Opcode("rst", "00h", "", 1)); //C7
		OpInfo00.Add(new Opcode("ret", "z", "", 1)); //C8
		OpInfo00.Add(new Opcode("ret", "n/a", "", 1)); //C9
		OpInfo00.Add(new Opcode("jp", "", "x4", 3)); //CA
		OpInfo00.Add(new Opcode("prefix", "cb", "", 1)); //CB
		OpInfo00.Add(new Opcode("call", "", "x4", 3)); //CC
		OpInfo00.Add(new Opcode("call", "", "x4", 3)); //CD
		OpInfo00.Add(new Opcode("adc", "a,", "x2", 2)); //CE
		OpInfo00.Add(new Opcode("rst", "08h", "", 1)); //CF
		OpInfo00.Add(new Opcode("ret", "nc", "", 1)); //D0
		OpInfo00.Add(new Opcode("pop", "de", "", 1)); //D1
		OpInfo00.Add(new Opcode("jp", "", "x4", 3)); //D2
		OpInfo00.Add(new Opcode("pre", "", "", 0)); //D3
		OpInfo00.Add(new Opcode("call", "", "x4", 3)); //D4
		OpInfo00.Add(new Opcode("push", "de", "", 1)); //D5
		OpInfo00.Add(new Opcode("sub", "", "x2", 2)); //D6
		OpInfo00.Add(new Opcode("rst", "10h", "", 1)); //D7
		OpInfo00.Add(new Opcode("ret", "c", "", 1)); //D8
		OpInfo00.Add(new Opcode("reti", "n/a", "", 1)); //D9
		OpInfo00.Add(new Opcode("jp", "", "x4", 3)); //DA
		OpInfo00.Add(new Opcode("pre", "", "", 0)); //DB
		OpInfo00.Add(new Opcode("call", "", "x4", 3)); //DC
		OpInfo00.Add(new Opcode("pre", "", "", 0)); //DD
		OpInfo00.Add(new Opcode("sbc", "a,", "x2", 2)); //DE
		OpInfo00.Add(new Opcode("rst", "18h", "", 1)); //DF
		OpInfo00.Add(new Opcode("ldh", "(a8),a", "", 2)); //E0
		OpInfo00.Add(new Opcode("pop", "hl", "", 1)); //E1
		OpInfo00.Add(new Opcode("ld", "(c),a", "", 2)); //E2
		OpInfo00.Add(new Opcode("pre", "", "", 0)); //E3
		OpInfo00.Add(new Opcode("pre", "", "", 0)); //E4
		OpInfo00.Add(new Opcode("push", "hl", "", 1)); //E5
		OpInfo00.Add(new Opcode("and", "", "x2", 2)); //E6
		OpInfo00.Add(new Opcode("rst", "20h", "", 1)); //E7
		OpInfo00.Add(new Opcode("add", "sp,", "x4", 2)); //E8
		OpInfo00.Add(new Opcode("jp", "(hl)", "", 1)); //E9
		OpInfo00.Add(new Opcode("ld", "a", "x4", 3)); //EA
		OpInfo00.Add(new Opcode("pre", "", "", 0)); //EB
		OpInfo00.Add(new Opcode("pre", "", "", 0)); //EC
		OpInfo00.Add(new Opcode("pre", "", "", 0)); //ED
		OpInfo00.Add(new Opcode("xor", "", "x2", 2)); //EE
		OpInfo00.Add(new Opcode("rst", "28h", "", 1)); //EF
		OpInfo00.Add(new Opcode("ldh", "a,(a8)", "", 2)); //F0
		OpInfo00.Add(new Opcode("pop", "af", "", 1)); //F1
		OpInfo00.Add(new Opcode("ld", "a,(c)", "", 2)); //F2
		OpInfo00.Add(new Opcode("di", "n/a", "", 1)); //F3
		OpInfo00.Add(new Opcode("pre", "", "", 0)); //F4
		OpInfo00.Add(new Opcode("push", "af", "", 1)); //F5
		OpInfo00.Add(new Opcode("or", "", "x2", 2)); //F6
		OpInfo00.Add(new Opcode("rst", "30h", "", 1)); //F7
		OpInfo00.Add(new Opcode("ld", "hl,sp+", "x4", 2)); //F8
		OpInfo00.Add(new Opcode("ld", "sp,hl", "", 1)); //F9
		OpInfo00.Add(new Opcode("ld", "()", "x4", 3)); //FA
		OpInfo00.Add(new Opcode("ei", "n/a", "", 1)); //FB
		OpInfo00.Add(new Opcode("pre", "", "", 0)); //FC
		OpInfo00.Add(new Opcode("pre", "", "", 0)); //FD
		OpInfo00.Add(new Opcode("cp", "", "x2", 2)); //FE
		OpInfo00.Add(new Opcode("rst", "38h", "", 1)); //FF
		OpInfoCB.Add(new Opcode("rlc", "b", "", 2)); //00
		OpInfoCB.Add(new Opcode("rlc", "c", "", 2)); //01
		OpInfoCB.Add(new Opcode("rlc", "d", "", 2)); //02
		OpInfoCB.Add(new Opcode("rlc", "e", "", 2)); //03
		OpInfoCB.Add(new Opcode("rlc", "h", "", 2)); //04
		OpInfoCB.Add(new Opcode("rlc", "l", "", 2)); //05
		OpInfoCB.Add(new Opcode("rlc", "(hl)", "", 2)); //06
		OpInfoCB.Add(new Opcode("rlc", "a", "", 2)); //07
		OpInfoCB.Add(new Opcode("rrc", "b", "", 2)); //08
		OpInfoCB.Add(new Opcode("rrc", "c", "", 2)); //09
		OpInfoCB.Add(new Opcode("rrc", "d", "", 2)); //0A
		OpInfoCB.Add(new Opcode("rrc", "e", "", 2)); //0B
		OpInfoCB.Add(new Opcode("rrc", "h", "", 2)); //0C
		OpInfoCB.Add(new Opcode("rrc", "l", "", 2)); //0D
		OpInfoCB.Add(new Opcode("rrc", "(hl)", "", 2)); //0E
		OpInfoCB.Add(new Opcode("rrc", "a", "", 2)); //0F
		OpInfoCB.Add(new Opcode("rl", "b", "", 2)); //10
		OpInfoCB.Add(new Opcode("rl", "c", "", 2)); //11
		OpInfoCB.Add(new Opcode("rl", "d", "", 2)); //12
		OpInfoCB.Add(new Opcode("rl", "e", "", 2)); //13
		OpInfoCB.Add(new Opcode("rl", "h", "", 2)); //14
		OpInfoCB.Add(new Opcode("rl", "l", "", 2)); //15
		OpInfoCB.Add(new Opcode("rl", "(hl)", "", 2)); //16
		OpInfoCB.Add(new Opcode("rl", "a", "", 2)); //17
		OpInfoCB.Add(new Opcode("rr", "b", "", 2)); //18
		OpInfoCB.Add(new Opcode("rr", "c", "", 2)); //19
		OpInfoCB.Add(new Opcode("rr", "d", "", 2)); //1A
		OpInfoCB.Add(new Opcode("rr", "e", "", 2)); //1B
		OpInfoCB.Add(new Opcode("rr", "h", "", 2)); //1C
		OpInfoCB.Add(new Opcode("rr", "l", "", 2)); //1D
		OpInfoCB.Add(new Opcode("rr", "(hl)", "", 2)); //1E
		OpInfoCB.Add(new Opcode("rr", "a", "", 2)); //1F
		OpInfoCB.Add(new Opcode("sla", "b", "", 2)); //20
		OpInfoCB.Add(new Opcode("sla", "c", "", 2)); //21
		OpInfoCB.Add(new Opcode("sla", "d", "", 2)); //22
		OpInfoCB.Add(new Opcode("sla", "e", "", 2)); //23
		OpInfoCB.Add(new Opcode("sla", "h", "", 2)); //24
		OpInfoCB.Add(new Opcode("sla", "l", "", 2)); //25
		OpInfoCB.Add(new Opcode("sla", "(hl)", "", 2)); //26
		OpInfoCB.Add(new Opcode("sla", "a", "", 2)); //27
		OpInfoCB.Add(new Opcode("sra", "b", "", 2)); //28
		OpInfoCB.Add(new Opcode("sra", "c", "", 2)); //29
		OpInfoCB.Add(new Opcode("sra", "d", "", 2)); //2A
		OpInfoCB.Add(new Opcode("sra", "e", "", 2)); //2B
		OpInfoCB.Add(new Opcode("sra", "h", "", 2)); //2C
		OpInfoCB.Add(new Opcode("sra", "l", "", 2)); //2D
		OpInfoCB.Add(new Opcode("sra", "(hl)", "", 2)); //2E
		OpInfoCB.Add(new Opcode("sra", "a", "", 2)); //2F
		OpInfoCB.Add(new Opcode("swap", "b", "", 2)); //30
		OpInfoCB.Add(new Opcode("swap", "c", "", 2)); //31
		OpInfoCB.Add(new Opcode("swap", "d", "", 2)); //32
		OpInfoCB.Add(new Opcode("swap", "e", "", 2)); //33
		OpInfoCB.Add(new Opcode("swap", "h", "", 2)); //34
		OpInfoCB.Add(new Opcode("swap", "l", "", 2)); //35
		OpInfoCB.Add(new Opcode("swap", "(hl)", "", 2)); //36
		OpInfoCB.Add(new Opcode("swap", "a", "", 2)); //37
		OpInfoCB.Add(new Opcode("srl", "b", "", 2)); //38
		OpInfoCB.Add(new Opcode("srl", "c", "", 2)); //39
		OpInfoCB.Add(new Opcode("srl", "d", "", 2)); //3A
		OpInfoCB.Add(new Opcode("srl", "e", "", 2)); //3B
		OpInfoCB.Add(new Opcode("srl", "h", "", 2)); //3C
		OpInfoCB.Add(new Opcode("srl", "l", "", 2)); //3D
		OpInfoCB.Add(new Opcode("srl", "(hl)", "", 2)); //3E
		OpInfoCB.Add(new Opcode("srl", "a", "", 2)); //3F
		OpInfoCB.Add(new Opcode("bit", "0,b", "", 2)); //40
		OpInfoCB.Add(new Opcode("bit", "0,c", "", 2)); //41
		OpInfoCB.Add(new Opcode("bit", "0,d", "", 2)); //42
		OpInfoCB.Add(new Opcode("bit", "0,e", "", 2)); //43
		OpInfoCB.Add(new Opcode("bit", "0,h", "", 2)); //44
		OpInfoCB.Add(new Opcode("bit", "0,l", "", 2)); //45
		OpInfoCB.Add(new Opcode("bit", "0,(hl)", "", 2)); //46
		OpInfoCB.Add(new Opcode("bit", "0,a", "", 2)); //47
		OpInfoCB.Add(new Opcode("bit", "1,b", "", 2)); //48
		OpInfoCB.Add(new Opcode("bit", "1,c", "", 2)); //49
		OpInfoCB.Add(new Opcode("bit", "1,d", "", 2)); //4A
		OpInfoCB.Add(new Opcode("bit", "1,e", "", 2)); //4B
		OpInfoCB.Add(new Opcode("bit", "1,h", "", 2)); //4C
		OpInfoCB.Add(new Opcode("bit", "1,l", "", 2)); //4D
		OpInfoCB.Add(new Opcode("bit", "1,(hl)", "", 2)); //4E
		OpInfoCB.Add(new Opcode("bit", "1,a", "", 2)); //4F
		OpInfoCB.Add(new Opcode("bit", "2,b", "", 2)); //50
		OpInfoCB.Add(new Opcode("bit", "2,c", "", 2)); //51
		OpInfoCB.Add(new Opcode("bit", "2,d", "", 2)); //52
		OpInfoCB.Add(new Opcode("bit", "2,e", "", 2)); //53
		OpInfoCB.Add(new Opcode("bit", "2,h", "", 2)); //54
		OpInfoCB.Add(new Opcode("bit", "2,l", "", 2)); //55
		OpInfoCB.Add(new Opcode("bit", "2,(hl)", "", 2)); //56
		OpInfoCB.Add(new Opcode("bit", "2,a", "", 2)); //57
		OpInfoCB.Add(new Opcode("bit", "3,b", "", 2)); //58
		OpInfoCB.Add(new Opcode("bit", "3,c", "", 2)); //59
		OpInfoCB.Add(new Opcode("bit", "3,d", "", 2)); //5A
		OpInfoCB.Add(new Opcode("bit", "3,e", "", 2)); //5B
		OpInfoCB.Add(new Opcode("bit", "3,h", "", 2)); //5C
		OpInfoCB.Add(new Opcode("bit", "3,l", "", 2)); //5D
		OpInfoCB.Add(new Opcode("bit", "3,(hl)", "", 2)); //5E
		OpInfoCB.Add(new Opcode("bit", "3,a", "", 2)); //5F
		OpInfoCB.Add(new Opcode("bit", "4,b", "", 2)); //60
		OpInfoCB.Add(new Opcode("bit", "4,c", "", 2)); //61
		OpInfoCB.Add(new Opcode("bit", "4,d", "", 2)); //62
		OpInfoCB.Add(new Opcode("bit", "4,e", "", 2)); //63
		OpInfoCB.Add(new Opcode("bit", "4,h", "", 2)); //64
		OpInfoCB.Add(new Opcode("bit", "4,l", "", 2)); //65
		OpInfoCB.Add(new Opcode("bit", "4,(hl)", "", 2)); //66
		OpInfoCB.Add(new Opcode("bit", "4,a", "", 2)); //67
		OpInfoCB.Add(new Opcode("bit", "5,b", "", 2)); //68
		OpInfoCB.Add(new Opcode("bit", "5,c", "", 2)); //69
		OpInfoCB.Add(new Opcode("bit", "5,d", "", 2)); //6A
		OpInfoCB.Add(new Opcode("bit", "5,e", "", 2)); //6B
		OpInfoCB.Add(new Opcode("bit", "5,h", "", 2)); //6C
		OpInfoCB.Add(new Opcode("bit", "5,l", "", 2)); //6D
		OpInfoCB.Add(new Opcode("bit", "5,(hl)", "", 2)); //6E
		OpInfoCB.Add(new Opcode("bit", "5,a", "", 2)); //6F
		OpInfoCB.Add(new Opcode("bit", "6,b", "", 2)); //70
		OpInfoCB.Add(new Opcode("bit", "6,c", "", 2)); //71
		OpInfoCB.Add(new Opcode("bit", "6,d", "", 2)); //72
		OpInfoCB.Add(new Opcode("bit", "6,e", "", 2)); //73
		OpInfoCB.Add(new Opcode("bit", "6,h", "", 2)); //74
		OpInfoCB.Add(new Opcode("bit", "6,l", "", 2)); //75
		OpInfoCB.Add(new Opcode("bit", "6,(hl)", "", 2)); //76
		OpInfoCB.Add(new Opcode("bit", "6,a", "", 2)); //77
		OpInfoCB.Add(new Opcode("bit", "7,b", "", 2)); //78
		OpInfoCB.Add(new Opcode("bit", "7,c", "", 2)); //79
		OpInfoCB.Add(new Opcode("bit", "7,d", "", 2)); //7A
		OpInfoCB.Add(new Opcode("bit", "7,e", "", 2)); //7B
		OpInfoCB.Add(new Opcode("bit", "7,h", "", 2)); //7C
		OpInfoCB.Add(new Opcode("bit", "7,l", "", 2)); //7D
		OpInfoCB.Add(new Opcode("bit", "7,(hl)", "", 2)); //7E
		OpInfoCB.Add(new Opcode("bit", "7,a", "", 2)); //7F
		OpInfoCB.Add(new Opcode("res", "0,b", "", 2)); //80
		OpInfoCB.Add(new Opcode("res", "0,c", "", 2)); //81
		OpInfoCB.Add(new Opcode("res", "0,d", "", 2)); //82
		OpInfoCB.Add(new Opcode("res", "0,e", "", 2)); //83
		OpInfoCB.Add(new Opcode("res", "0,h", "", 2)); //84
		OpInfoCB.Add(new Opcode("res", "0,l", "", 2)); //85
		OpInfoCB.Add(new Opcode("res", "0,(hl)", "", 2)); //86
		OpInfoCB.Add(new Opcode("res", "0,a", "", 2)); //87
		OpInfoCB.Add(new Opcode("res", "1,b", "", 2)); //88
		OpInfoCB.Add(new Opcode("res", "1,c", "", 2)); //89
		OpInfoCB.Add(new Opcode("res", "1,d", "", 2)); //8A
		OpInfoCB.Add(new Opcode("res", "1,e", "", 2)); //8B
		OpInfoCB.Add(new Opcode("res", "1,h", "", 2)); //8C
		OpInfoCB.Add(new Opcode("res", "1,l", "", 2)); //8D
		OpInfoCB.Add(new Opcode("res", "1,(hl)", "", 2)); //8E
		OpInfoCB.Add(new Opcode("res", "1,a", "", 2)); //8F
		OpInfoCB.Add(new Opcode("res", "2,b", "", 2)); //90
		OpInfoCB.Add(new Opcode("res", "2,c", "", 2)); //91
		OpInfoCB.Add(new Opcode("res", "2,d", "", 2)); //92
		OpInfoCB.Add(new Opcode("res", "2,e", "", 2)); //93
		OpInfoCB.Add(new Opcode("res", "2,h", "", 2)); //94
		OpInfoCB.Add(new Opcode("res", "2,l", "", 2)); //95
		OpInfoCB.Add(new Opcode("res", "2,(hl)", "", 2)); //96
		OpInfoCB.Add(new Opcode("res", "2,a", "", 2)); //97
		OpInfoCB.Add(new Opcode("res", "3,b", "", 2)); //98
		OpInfoCB.Add(new Opcode("res", "3,c", "", 2)); //99
		OpInfoCB.Add(new Opcode("res", "3,d", "", 2)); //9A
		OpInfoCB.Add(new Opcode("res", "3,e", "", 2)); //9B
		OpInfoCB.Add(new Opcode("res", "3,h", "", 2)); //9C
		OpInfoCB.Add(new Opcode("res", "3,l", "", 2)); //9D
		OpInfoCB.Add(new Opcode("res", "3,(hl)", "", 2)); //9E
		OpInfoCB.Add(new Opcode("res", "3,a", "", 2)); //9F
		OpInfoCB.Add(new Opcode("res", "4,b", "", 2)); //A0
		OpInfoCB.Add(new Opcode("res", "4,c", "", 2)); //A1
		OpInfoCB.Add(new Opcode("res", "4,d", "", 2)); //A2
		OpInfoCB.Add(new Opcode("res", "4,e", "", 2)); //A3
		OpInfoCB.Add(new Opcode("res", "4,h", "", 2)); //A4
		OpInfoCB.Add(new Opcode("res", "4,l", "", 2)); //A5
		OpInfoCB.Add(new Opcode("res", "4,(hl)", "", 2)); //A6
		OpInfoCB.Add(new Opcode("res", "4,a", "", 2)); //A7
		OpInfoCB.Add(new Opcode("res", "5,b", "", 2)); //A8
		OpInfoCB.Add(new Opcode("res", "5,c", "", 2)); //A9
		OpInfoCB.Add(new Opcode("res", "5,d", "", 2)); //AA
		OpInfoCB.Add(new Opcode("res", "5,e", "", 2)); //AB
		OpInfoCB.Add(new Opcode("res", "5,h", "", 2)); //AC
		OpInfoCB.Add(new Opcode("res", "5,l", "", 2)); //AD
		OpInfoCB.Add(new Opcode("res", "5,(hl)", "", 2)); //AE
		OpInfoCB.Add(new Opcode("res", "5,a", "", 2)); //AF
		OpInfoCB.Add(new Opcode("res", "6,b", "", 2)); //B0
		OpInfoCB.Add(new Opcode("res", "6,c", "", 2)); //B1
		OpInfoCB.Add(new Opcode("res", "6,d", "", 2)); //B2
		OpInfoCB.Add(new Opcode("res", "6,e", "", 2)); //B3
		OpInfoCB.Add(new Opcode("res", "6,h", "", 2)); //B4
		OpInfoCB.Add(new Opcode("res", "6,l", "", 2)); //B5
		OpInfoCB.Add(new Opcode("res", "6,(hl)", "", 2)); //B6
		OpInfoCB.Add(new Opcode("res", "6,a", "", 2)); //B7
		OpInfoCB.Add(new Opcode("res", "7,b", "", 2)); //B8
		OpInfoCB.Add(new Opcode("res", "7,c", "", 2)); //B9
		OpInfoCB.Add(new Opcode("res", "7,d", "", 2)); //BA
		OpInfoCB.Add(new Opcode("res", "7,e", "", 2)); //BB
		OpInfoCB.Add(new Opcode("res", "7,h", "", 2)); //BC
		OpInfoCB.Add(new Opcode("res", "7,l", "", 2)); //BD
		OpInfoCB.Add(new Opcode("res", "7,(hl)", "", 2)); //BE
		OpInfoCB.Add(new Opcode("res", "7,a", "", 2)); //BF
		OpInfoCB.Add(new Opcode("set", "0,b", "", 2)); //C0
		OpInfoCB.Add(new Opcode("set", "0,c", "", 2)); //C1
		OpInfoCB.Add(new Opcode("set", "0,d", "", 2)); //C2
		OpInfoCB.Add(new Opcode("set", "0,e", "", 2)); //C3
		OpInfoCB.Add(new Opcode("set", "0,h", "", 2)); //C4
		OpInfoCB.Add(new Opcode("set", "0,l", "", 2)); //C5
		OpInfoCB.Add(new Opcode("set", "0,(hl)", "", 2)); //C6
		OpInfoCB.Add(new Opcode("set", "0,a", "", 2)); //C7
		OpInfoCB.Add(new Opcode("set", "1,b", "", 2)); //C8
		OpInfoCB.Add(new Opcode("set", "1,c", "", 2)); //C9
		OpInfoCB.Add(new Opcode("set", "1,d", "", 2)); //CA
		OpInfoCB.Add(new Opcode("set", "1,e", "", 2)); //CB
		OpInfoCB.Add(new Opcode("set", "1,h", "", 2)); //CC
		OpInfoCB.Add(new Opcode("set", "1,l", "", 2)); //CD
		OpInfoCB.Add(new Opcode("set", "1,(hl)", "", 2)); //CE
		OpInfoCB.Add(new Opcode("set", "1,a", "", 2)); //CF
		OpInfoCB.Add(new Opcode("set", "2,b", "", 2)); //D0
		OpInfoCB.Add(new Opcode("set", "2,c", "", 2)); //D1
		OpInfoCB.Add(new Opcode("set", "2,d", "", 2)); //D2
		OpInfoCB.Add(new Opcode("set", "2,e", "", 2)); //D3
		OpInfoCB.Add(new Opcode("set", "2,h", "", 2)); //D4
		OpInfoCB.Add(new Opcode("set", "2,l", "", 2)); //D5
		OpInfoCB.Add(new Opcode("set", "2,(hl)", "", 2)); //D6
		OpInfoCB.Add(new Opcode("set", "2,a", "", 2)); //D7
		OpInfoCB.Add(new Opcode("set", "3,b", "", 2)); //D8
		OpInfoCB.Add(new Opcode("set", "3,c", "", 2)); //D9
		OpInfoCB.Add(new Opcode("set", "3,d", "", 2)); //DA
		OpInfoCB.Add(new Opcode("set", "3,e", "", 2)); //DB
		OpInfoCB.Add(new Opcode("set", "3,h", "", 2)); //DC
		OpInfoCB.Add(new Opcode("set", "3,l", "", 2)); //DD
		OpInfoCB.Add(new Opcode("set", "3,(hl)", "", 2)); //DE
		OpInfoCB.Add(new Opcode("set", "3,a", "", 2)); //DF
		OpInfoCB.Add(new Opcode("set", "4,b", "", 2)); //E0
		OpInfoCB.Add(new Opcode("set", "4,c", "", 2)); //E1
		OpInfoCB.Add(new Opcode("set", "4,d", "", 2)); //E2
		OpInfoCB.Add(new Opcode("set", "4,e", "", 2)); //E3
		OpInfoCB.Add(new Opcode("set", "4,h", "", 2)); //E4
		OpInfoCB.Add(new Opcode("set", "4,l", "", 2)); //E5
		OpInfoCB.Add(new Opcode("set", "4,(hl)", "", 2)); //E6
		OpInfoCB.Add(new Opcode("set", "4,a", "", 2)); //E7
		OpInfoCB.Add(new Opcode("set", "5,b", "", 2)); //E8
		OpInfoCB.Add(new Opcode("set", "5,c", "", 2)); //E9
		OpInfoCB.Add(new Opcode("set", "5,d", "", 2)); //EA
		OpInfoCB.Add(new Opcode("set", "5,e", "", 2)); //EB
		OpInfoCB.Add(new Opcode("set", "5,h", "", 2)); //EC
		OpInfoCB.Add(new Opcode("set", "5,l", "", 2)); //ED
		OpInfoCB.Add(new Opcode("set", "5,(hl)", "", 2)); //EE
		OpInfoCB.Add(new Opcode("set", "5,a", "", 2)); //EF
		OpInfoCB.Add(new Opcode("set", "6,b", "", 2)); //F0
		OpInfoCB.Add(new Opcode("set", "6,c", "", 2)); //F1
		OpInfoCB.Add(new Opcode("set", "6,d", "", 2)); //F2
		OpInfoCB.Add(new Opcode("set", "6,e", "", 2)); //F3
		OpInfoCB.Add(new Opcode("set", "6,h", "", 2)); //F4
		OpInfoCB.Add(new Opcode("set", "6,l", "", 2)); //F5
		OpInfoCB.Add(new Opcode("set", "6,(hl)", "", 2)); //F6
		OpInfoCB.Add(new Opcode("set", "6,a", "", 2)); //F7
		OpInfoCB.Add(new Opcode("set", "7,b", "", 2)); //F8
		OpInfoCB.Add(new Opcode("set", "7,c", "", 2)); //F9
		OpInfoCB.Add(new Opcode("set", "7,d", "", 2)); //FA
		OpInfoCB.Add(new Opcode("set", "7,e", "", 2)); //FB
		OpInfoCB.Add(new Opcode("set", "7,h", "", 2)); //FC
		OpInfoCB.Add(new Opcode("set", "7,l", "", 2)); //FD
		OpInfoCB.Add(new Opcode("set", "7,(hl)", "", 2)); //FE
		OpInfoCB.Add(new Opcode("set", "7,a", "", 2)); //FF
	}
}

