global using Gmulator.Shared;
global using Gmulator.Ui;
global using Raylib_cs;
global using System.IO;
global using System.Text;
global using static Gmulator.JsonUtil;
global using static Gmulator.Shared.ByteExtensions;
global using static Gmulator.Shared.Constants;
global using static Gmulator.Shared.EmuState;
global using static Gmulator.Ui.GuiUtils;
